### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by tonitch** [MokonaNico/NovaPlanning#23]
Hey,
I would like to contribute to the project (as I understand it, https://github.com/shinkumons/NovaPlanning/ is the main fork of it) I also want to re-use some of the code for one of my own project.

But the project doesn't have any licenses. by that it means that the project is strictly in your possesion and therefore can't be copied (not even used) by anyone on the internet. can you please choose a license that would allow us to use and share your code ? if you don't know what to use you could look for the "MIT license" which basicly say: do whatever you want with the code. or the "GPL license" which say: do whatever you want as long as you use the same license therefore it should stay open source. ^^ 
Thanks a bunch!
(@Shinkumons I know you know him and I want to ask  you too but I think this one is the original piece of code so I ask here ^^)

**Comment by MokonaNico** [comment]
Thanks for your interest and for reaching out. I've added an MIT license to the project, so feel free to use and share the code.
