### ISSUE TITLE
Site blanc

### ISSUE THREAD

**Issue by fadri14** [MokonaNico/NovaPlanning#24]
Salut,

J'ai sélectionné les cours que je souhaitais mais une fois que je clique sur le bouton retour, j'arrive sur une page blanche et je ne peux donc pas télécharger le ical comme souhaité.

Merci à ceux que prendront le temps de m'aider

**Comment by MokonaNico** [comment]
Salut,

Tu peux donner plus d'info sur le problème. Est-ce que tu peux le reproduire ? Ton navigateur ? Message d'erreur dans la console ?

**Comment by fadri14** [comment]
Et pour reproduire l'erreur.
Je sélectionne tout simplement mes en info, bac 2 et 3. Ensuite j'appuie sur le bouton retour et j'arrive sur une page blanche avec l'erreur en console

**Comment by MokonaNico** [comment]
J'ai l'impression que le problème apparaît lorsque l'on sélectionne "Tout sélectionner".

Je vais réparer ça ce soir. Si tu veux pouvoir utiliser le planning d'ici là, tu peux simplement sélectionner chaque cours un par un.

**Comment by fadri14** [comment]
Effectivement, maintenant je n'ai plus la page blanche. Merci pour ta réponse

**Comment by MokonaNico** [comment]
Voila le problème est fix
